### ISSUE TITLE
你好，我公司招收一批逆向开发个人开发者，希望联系。工资7000起步封顶22000，可以匿名工作，也可以签合同正规体现在合同内。

### ISSUE THREAD

**Issue by cha222554** [FiYHer/Game-Cheating-Tutorial#1]
你好，我公司招收一批逆向开发个人开发者，希望联系。工资7000起步封顶22000，可以匿名工作，也可以签合同正规体现在合同内。
邮箱：mua@mua.pub你好，我公司招收一批逆向开发个人开发者，希望联系。工资7000起步封顶22000，可以匿名工作，也可以签合同正规体现在合同内。

**Comment by cha222554** [comment]
希望联系。谢谢非机器人

**Comment by FiYHer** [comment]
> 希望联系。谢谢非机器人

怎么联系

**Comment by wyz155** [comment]
> > 希望联系。谢谢非机器人
> 
> 怎么联系

你好加我下QQ 1173760692

**Comment by cha222554** [comment]
> > 希望联系。谢谢非机器人
> 
> 怎么联系

请留下Telegram或discord账户。谢谢。

**Comment by cha222554** [comment]
> > > 希望联系。谢谢非机器人
> > 
> > 
> > 怎么联系
> 
> 你好加我下QQ 1173760692

请留下Telegram或discord账户。谢谢。

**Comment by cha222554** [comment]
> > 希望联系。谢谢非机器人
> 
> 怎么联系

我的discord ：mianbai#4578
Telegram : @mianbai
Email : wzjiance@outlook.com
QQ : 17996197
