### ISSUE TITLE
大神，有CF的绕过TP检测的代码么

### ISSUE THREAD

**Issue by mSoftDeveloper** [FiYHer/Game-Cheating-Tutorial#11]

**Comment by FiYHer** [comment]
1.驱动读写
2.驱动读写 驱动隐藏
3.驱动读写 驱动隐藏 清理痕迹
4.手动映射驱动读写 清理痕迹
5.内核回调覆盖
6.UEFI

**Comment by FiYHer** [comment]
没看过tp，国外讨论蛮少的，但应该上面的方法是有用的，这些方法be和eac都能过，看你怎么用了
