### ISSUE TITLE
Do you have tutorial for dota 2?

### ISSUE THREAD

**Issue by aspoofer0224** [FiYHer/Game-Cheating-Tutorial#13]

**Comment by FiYHer** [comment]
I'm sorry, I don't have data2 tutorial. I'm only interested in fps games

**Comment by WWFWT** [comment]
没有。。------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;fengyihua&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月27日(星期五) 中午11:27
收件人:&nbsp;&quot;FiYHer/Game-Cheating-Tutorial&quot;<Game-Cheating-Tutorial@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [FiYHer/Game-Cheating-Tutorial] Do you have tutorial for dota 2? (#13)

**Comment by FiYHer** [comment]
> 没有。。------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;&quot;fengyihua&quot;<notifications@github.com&gt; 发送时间:&nbsp;2020年11月27日(星期五) 中午11:27 收件人:&nbsp;&quot;FiYHer/Game-Cheating-Tutorial&quot;<Game-Cheating-Tutorial@noreply.github.com&gt;; 抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;; 主题:&nbsp;Re: [FiYHer/Game-Cheating-Tutorial] Do you have tutorial for dota 2? (#13)

你不是无法无天嘛?你搞到哪里了?

**Comment by WWFWT** [comment]
是呀，但是Dota2我连玩都没玩过呢|ω・）------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;fengyihua&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月27日(星期五) 中午11:42
收件人:&nbsp;&quot;FiYHer/Game-Cheating-Tutorial&quot;<Game-Cheating-Tutorial@noreply.github.com&gt;;
抄送:&nbsp;&quot;吾无法无天&quot;<983232901@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [FiYHer/Game-Cheating-Tutorial] Do you have tutorial for dota 2? (#13)
