### ISSUE TITLE
老哥有没有考虑整整单机版的塔科夫

### ISSUE THREAD

**Issue by TWENTYERSHI** [FiYHer/Game-Cheating-Tutorial#16]
RT.看完老哥的csgo的视频之后，受益匪浅。但是对于单机塔科夫这种类型的游戏完全没有思路。
老哥有空整一波吗，刚好嫖一下思路

**Comment by Clownsw** [comment]
我记得塔科夫不是.Net

**Comment by TWENTYERSHI** [comment]
> 我记得塔科夫不是.Net

塔科夫是Unity做的

**Comment by FiYHer** [comment]
> RT.看完老哥的csgo的视频之后，受益匪浅。但是对于单机塔科夫这种类型的游戏完全没有思路。
> 老哥有空整一波吗，刚好嫖一下思路

为什么要搞单机版，联网的不是更好玩嘛

**Comment by TWENTYERSHI** [comment]
> > RT.看完老哥的csgo的视频之后，受益匪浅。但是对于单机塔科夫这种类型的游戏完全没有思路。
> > 老哥有空整一波吗，刚好嫖一下思路
> 
> 为什么要搞单机版，联网的不是更好玩嘛

单机版没有反作弊，感觉适合练手，联网的我怕不是一个月买号就得花不少（
![image](https://user-images.githubusercontent.com/75521425/102765244-50497680-43b7-11eb-842e-103ed44b00ef.png)

**Comment by FiYHer** [comment]
> > > RT.看完老哥的csgo的视频之后，受益匪浅。但是对于单机塔科夫这种类型的游戏完全没有思路。
> > > 老哥有空整一波吗，刚好嫖一下思路
> > 
> > 
> > 为什么要搞单机版，联网的不是更好玩嘛
> 
> 单机版没有反作弊，感觉适合练手，联网的我怕不是一个月买号就得花不少（
> ![image](https://user-images.githubusercontent.com/75521425/102765244-50497680-43b7-11eb-842e-103ed44b00ef.png)

有时间可以去看看呀

**Comment by TWENTYERSHI** [comment]
> > > > RT.看完老哥的csgo的视频之后，受益匪浅。但是对于单机塔科夫这种类型的游戏完全没有思路。
> > > > 老哥有空整一波吗，刚好嫖一下思路
> > > 
> > > 
> > > 为什么要搞单机版，联网的不是更好玩嘛
> > 
> > 
> > 单机版没有反作弊，感觉适合练手，联网的我怕不是一个月买号就得花不少（
> > ![image](https://user-images.githubusercontent.com/75521425/102765244-50497680-43b7-11eb-842e-103ed44b00ef.png)
> 
> 有时间可以去看看呀

嘿嘿，期待
