### ISSUE TITLE
It was great. It helped me a lot

### ISSUE THREAD

**Issue by Psycho-bit** [FiYHer/Game-Cheating-Tutorial#8]
Hopefully we'll talk more about that  and I still want to know how to circumvent the anti-cheating

**Comment by FiYHer** [comment]
> Hopefully we'll talk more about that and I still want to know how to circumvent the anti-cheating

about BE or EAC or...

**Comment by Psycho-bit** [comment]
> > 希望我们会更多地谈论这一点，我仍然想知道如何规避反作弊
> 
> 关于BE或EAC或...

HHHH  BE VAC 5E  A lot of anti-cheating needs to be done     in bilibili ， I tried to contact you  ，so  Can you leave a contact information  
QQ  or  QQ Group

**Comment by FiYHer** [comment]
> > > 希望我们会更多地谈论这一点，我仍然想知道如何规避反作弊
> > 
> > 
> > 关于BE或EAC或...
> 
> HHHH BE VAC 5E A lot of anti-cheating needs to be done in bilibili ， I tried to contact you ，so Can you leave a contact information
> QQ or QQ Group

5E does not have driver protection, it seems easy to bypass it, but it is difficult to find the address it changed.

**Comment by FiYHer** [comment]
> > > 希望我们会更多地谈论这一点，我仍然想知道如何规避反作弊
> > 
> > 
> > 关于BE或EAC或...
> 
> HHHH BE VAC 5E A lot of anti-cheating needs to be done in bilibili ， I tried to contact you ，so Can you leave a contact information
> QQ or QQ Group

QQ : 2653290887

**Comment by Psycho-bit** [comment]
It's really great. Look forward to your next project  
I'm a college student, too
Learn slowly and grow slowly
