### ISSUE TITLE
Silent Aimbot for CSGO

### ISSUE THREAD

**Issue by xhzn** [FiYHer/Game-Cheating-Tutorial#9]
我想学一下静默自瞄，我找不到相关的教程。

**Comment by FiYHer** [comment]
> 我想学一下静默自瞄，我找不到相关的教程。

Osiris的现成代码,自己看嘛
https://github.com/danielkrupinski/Osiris/blob/master/Osiris/Hacks/Aimbot.cpp#L100

**Comment by xhzn** [comment]
感谢。
